name: Build and Deploy MindTrack Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t mindtrack/mindtracking-front:latest .

      - name: Push image to Docker Hub
        run: docker push mindtrack/mindtracking-front:latest

  deploy:
    needs: build
    runs-on: [self-hosted, aws-ec2-front]
    steps:
      - name: Create Docker network (if not exists)
        run: |
          if ! docker network inspect mindtrack-net &> /dev/null; then
            docker network create mindtrack-net;
          fi

      - name: Stop and remove old container (if running)
        run: |
          docker stop mindtracking-front || true
          docker rm mindtracking-front || true

      - name: Pull latest image from Docker Hub
        run: docker pull mindtrack/mindtracking-front:latest

      - name: Run new container
        run: |
          docker run -d \
            --restart always \
            --name mindtracking-front \
            --network mindtrack-net \
            -p 80:80 \
            mindtrack/mindtracking-front:latest
